config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #STATIC pages
  
  get "/", to: "pages#welcome", as: "root"
  get "/home", to: "pages#home", as: "home"
  get "/explore", to: "pages#explore", as: "explore"
  # get "/learn", to: "pages#learn", as: "learn" #this was a sprinkle
  get "/contact", to: "pages#contact", as: "contact"

  # FILTER RESULTS

  get "/results/all", to: "contents#index", as: "results_all"
  get "/results/genres", to: "genres#index", as: "genres"
  get "/results/genres/:id", to: "genres#filter", as: "genre"
  get "/results/mediums", to: "mediums#index", as: "mediums"
  get "/results/mediums/:id", to: "mediums#filter", as: "medium"
  get "/results/artists", to: "artists#index", as: "artists"
  get "/contents", to: "contents#index", as: "contents"

  # ARTWORK CRUD

  get "/results/artwork/:id", to: "contents#show", as: "content"
  get "/sell", to: "contents#new", as: "new_content"
  post "/contents", to: "contents#create"
  get "/results/artwork/:id/edit", to: "contents#edit", as: "edit_content"
  patch "/results/artwork/:id", to: "contents#update"
  delete "/results/artwork/:id", to: "contents#destroy", as: "delete_content"

  #PAYMENT

  get "/orders/success", to: "orders#success", as: "payment_success"
  post "/webhook", to: "orders#webhook", as: "order"

 #PROFILE CRUD
  get "/profile", to: "profiles#index", as: "profile"
  get "/profile/edit", to: "profiles#edit", as: "edit_profile"
  get "/profile/:id", to: "artists#show", as: "profile_id"
  patch "/profile", to: "profiles#update"
  delete "/profile", to: "profiles#destroy", as: "delete_profile"

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :set_user_content, only: [:edit, :update, :delete]
    before_action :authenticate_user!, only: [:edit, :update, :destroy]


    def index
        @content = Content.all
        @user_content = current_user.contents
    end

    def show 
        @user = User.find_by_id(params[:id])
    end
    def edit

    end

    def update
        redirect_to profile_path
    end

    def destory
    end

    def set_user_content
        @content =  current_user.contents.find_by_id(params[:id])
    end
end

app/views/profiles/edit.html.erb
<main id="profile-edit-page">    

    <%= render "/nav_bar" %>

    <h2 class="heading">Edit your profile</h2>

    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
    <%= render "devise/shared/error_messages", resource: resource %>

        <div class="pic-upload">
        <%= f.file_field :pic, accept: "image/png,image/gif,image/jpeg,image/jpg", class: "upload" %>
        </div>
    
    <div class="text-field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
    </div>

    <div class="text-field">
        <%= f.label :username %><br />
        <%= f.text_field :username, autofocus: true, autocomplete: "username" %>
    </div>
    
    <div class="text-field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
    <% end %>

        <div class="text-field">
        <%= f.label :Bio %><br />
        <%= f.text_area :bio, autofocus: true, autocomplete: "enter a bio here!" %>
    </div>

    <div class="text-field"">
        <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
        <%= f.password_field :password, autocomplete: "new-password" %>
        <% if @minimum_password_length %>
        <br />
        <em><%= @minimum_password_length %> characters minimum</em>
        <% end %>
    </div>

    <div class="text-field"">
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="text-field"">
        <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
        <%= f.password_field :current_password, autocomplete: "current-password" %>
    </div>

    <div class="submit">
        <%= f.submit "Update" %>
    </div>
    <% end %>

    <h3>Delete my account</h3>

    <p>Want to leave The Art Club?</p>
    <p> <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: "cancel-button" %></p>
    <footer>
    </footer>

</main>

app/views/profiles/index.html.erb
<div id="profile">

    <%= render "/nav_bar" %>

    <!-- image uploaded by user or default image -->
    
    <div class="profile-picture">
        <% if current_user.pic.attached? %>
            <div class="pic-div"><%=image_tag current_user.pic, class: "user-pic"%></div>
            <p class="button"><%= link_to "edit profile", edit_profile_path, class: "edit-profile" %></p>
        <% else %>
            <div class="place-holder"></div>
                <p><%= link_to "change display picture", edit_profile_path %></p>
        <%end %>
    </div>

    <p class="button"><%= link_to 'logout', destroy_user_session_path, method: :delete, class: "log-out" %></p>



    <h1> <%=current_user.username%> </h1>

    <p> 
        <% if current_user.bio == nil %>
            <p><%= link_to "write a bio", edit_profile_path %></p>
        <% else %>
            <%=current_user.bio%>
        <%end %>
    </p>

    <div class="line"></div>

    <!-- then feed of Content uploaded with titles and prices -->
    <div class="user-art">
        <h2><%=current_user.name%>'s work</h2>

            <div class="flexbox">
                <% @user_content.each do |artwork| %>
                    <div class="listings">
                        <%=link_to content_path(artwork), class: "link-to" do %>
                            <%= image_tag artwork.pic if artwork.pic.attached? %>
                            <h2>
                            <%= artwork.title %>
                            </h2>
                            <p><%= number_to_currency(artwork.price / 100.0) %></p>
                        <%end%>
                    </div> 
                <% end %>
            </div>
    </div>
</div>