config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #STATIC pages
  
  get "/", to: "pages#welcome", as: "root"
  get "/home", to: "pages#home", as: "home"
  get "/explore", to: "pages#explore", as: "explore"
  # get "/learn", to: "pages#learn", as: "learn" #this was a sprinkle
  get "/contact", to: "pages#contact", as: "contact"

  # FILTER RESULTS

  get "/results/all", to: "contents#index", as: "results_all"
  get "/results/genres", to: "genres#index", as: "genres"
  get "/results/genres/:id", to: "genres#filter", as: "genre"
  get "/results/mediums", to: "mediums#index", as: "mediums"
  get "/results/mediums/:id", to: "mediums#filter", as: "medium"
  get "/results/artists", to: "artists#index", as: "artists"
  get "/contents", to: "contents#index", as: "contents"

  # ARTWORK CRUD

  get "/results/artwork/:id", to: "contents#show", as: "content"
  get "/sell", to: "contents#new", as: "new_content"
  post "/contents", to: "contents#create"
  get "/results/artwork/:id/edit", to: "contents#edit", as: "edit_content"
  patch "/results/artwork/:id", to: "contents#update"
  delete "/results/artwork/:id", to: "contents#destroy", as: "delete_content"

  #PAYMENT

  get "/orders/success", to: "orders#success", as: "payment_success"
  post "/webhook", to: "orders#webhook", as: "order"

 #PROFILE CRUD
  get "/profile", to: "profiles#index", as: "profile"
  get "/profile/edit", to: "profiles#edit", as: "edit_profile"
  get "/profile/:id", to: "artists#show", as: "profile_id"
  patch "/profile", to: "profiles#update"
  delete "/profile", to: "profiles#destroy", as: "delete_profile"

end

app/models/content.rb
class Content < ApplicationRecord
  validates :title, :genres, :mediums, :price, :pic, presence: true
  belongs_to :user
  has_many :contents_genres, dependent: :destroy
  has_many :genres, through: :contents_genres
  has_many :contents_mediums, dependent: :destroy
  has_many :mediums, through: :contents_mediums
  has_one_attached :pic
  has_one :order
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

    before_action :set_user_content, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def index
        # @artworks_all = Content.all #collects all artwork data and stores in instand variable @artworks_all
        search = params[:search]
        
        if search
            @artworks_all = Content.where("lower(title) LIKE ?", "%#{search.downcase}%")

        else 
            @artworks_all = Content.all
        end
    end
    
    def show
        @content = Content.find_by_id(params[:id])

        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: [{
                name: @content.title,
                amount: @content.price,
                currency: 'aud',
                quantity: 1,
            }],
            payment_intent_data: {
                metadata: {
                    user_id: current_user.id,
                    content_id: @content.id
                }
            },
            success_url: root_url + "orders/success",
            cancel_url: root_url + "results_all",
        )

    @session_id = session.id
    end

    def new
        @content = Content.new
        @genres = Genre.all
        @mediums = Medium.all
    end

    def create

        @artwork = Content.new(content_params)
        @artwork.user_id = current_user.id
        
        if @artwork.save
            redirect_to content_path(@artwork)
        else 
            @content = Content.new
            @genres = Genre.all
            @mediums = Medium.all 
            render "new"
        end
    end

    def edit
        @genres = Genre.all
        @mediums = Medium.all  
    end

    def update        
        if @content.update(content_params)
            redirect_to content_path(params[:id])
        else
            @genres = Genre.all
            @mediums = Medium.all             
            render "edit"
        end
    end

    def destroy
        @content =  current_user.contents.find_by_id(params[:id])
        @content.destroy
    end

    def set_user_content
        @content =  current_user.contents.find_by_id(params[:id])

        if @content == nil
            redirect_to results_all_path
        end
    end

    def content_params
        params.require(:content).permit(:title, :price, :pic, genre_ids:[], medium_ids:[])
    end

    def translate_params
        params[:content][:price] = (params[:content][:price].to_f * 100).to_i
    end

end

app/views/contents/destroy.html.erb
<main id="delete-page">
    <%= render "/nav_bar" %>

    <h1> Your content was successfully deleted!</h1>

    <%= link_to "Back to results", results_all_path, class: "button"%>
    
</main>

app/views/contents/edit.html.erb
<main id="edit-page">

    <%= render "/nav_bar" %>

    <div class="heading">
        <h1> Edit Artwork </h1>
    </div>

    <%= render "/form", content:@content %>

    <footer>
    </footer>

</main>

app/views/contents/index.html.erb
<main id="results">

    <%= render "/nav_bar" %>

    <div class="heading">
        <h1>All results</h1>
    </div>
    
    <%= render "/back_button" %>

        <!-- insert nav bar here -->
        <nav class="category-search">
            <div class="nav-element">
                <p><%= link_to "genre", genres_path,  :class => "link-to" %></p>
                <p><%= link_to "artist", artists_path, :class => "link-to"%></p>
                <p><%= link_to "medium", mediums_path, :class => "link-to"%></p>
                <p><%= link_to "all", results_all_path, :class => "link-to"%></p>

            </div>
        </nav>    

    <%= render "/listings" %>

</main>

app/views/contents/new.html.erb
<main id="sell-page">    

    <%= render "/nav_bar" %>
    
    <div class="heading">
        <h1> got artwork to sell? do it here! </h1>
    </div>

    <%= render "/form" %>

</main>

app/views/contents/results_all.html.erb
<main id="results">

    <%= render "/nav_bar" %>

    <h1> All results </h1>

    <%= render "/back_button" %>


        <!-- insert nav bar here -->
        <nav class="category-search">
            <div class="nav-element">
                <p><%= link_to "genre", genres_path,  :class => "link-to" %></p>
                <p><%= link_to "artist", artists_path, :class => "link-to"%></p>
                <p><%= link_to "medium", mediums_path, :class => "link-to"%></p>
            </div>
        </nav>    

    <%= render "/listings" %>

</main>

app/views/contents/show.html.erb
<div id="show">
    <%= render "/nav_bar" %>

    <div class="flexbox">
    <!-- artwork image -->
        <div class="artwork-image">
            <%= image_tag @content.pic if @content.pic.attached? %>
             <h2>
                <%= @content.title %>
            </h2>

        </div>

        <!-- artwork deets -->
        <section class="artwork-details">
            <h3>Price:</h3>
            <p>
                $<%=@content.price / 100.to_f %>
                <% unless @content.order %>
                    <button data-stripe="buy">Buy Now!</button>
                <% end %>
            </p>

            <h3>Artist:</h3>
            <p><%= @content.user.username %><p>
            
            
            <h3>Genre:</h3>

            <p>
                <% if @content.genres.length == 0 %>
                    <p> None listed </p>
                <%else%>
                    <% @content.genres.each do |genre| %>
                    <%= genre.title %>, 
                    <%end %>
                <%end%>
            </p>

            <h3>Medium:</h3>

            <p>
                <% if @content.mediums.length == 0 %>
                    <p> None listed </p>
                <%else%>
                    <% @content.mediums.each do |medium| %>
                        <%= medium.material%>,
                    <%end%>
                <%end %>
            </p>
        </section>

        <script src="https://js.stripe.com/v3/"></script>

        <script>
            document.querySelector("[data-stripe='buy']").addEventListener("click", () => {
                const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
                
                stripe.redirectToCheckout({
                sessionId: "<%= @session_id %>"
                });
            });
        </script>
    </div>

    <section class="bottom-buttons">
        <button><%= link_to 'Edit', edit_content_path(@content) if user_signed_in? and @content.user_id == current_user.id %> </button>
         <button><%= link_to 'Destroy', @content, method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? and @content.user_id == current_user.id %></button>
         <button><%= link_to 'Back', results_all_path %></button>
    </section>
</div>
    