config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #STATIC pages
  
  get "/", to: "pages#welcome", as: "root"
  get "/home", to: "pages#home", as: "home"
  get "/explore", to: "pages#explore", as: "explore"
  # get "/learn", to: "pages#learn", as: "learn" #this was a sprinkle
  get "/contact", to: "pages#contact", as: "contact"

  # FILTER RESULTS

  get "/results/all", to: "contents#index", as: "results_all"
  get "/results/genres", to: "genres#index", as: "genres"
  get "/results/genres/:id", to: "genres#filter", as: "genre"
  get "/results/mediums", to: "mediums#index", as: "mediums"
  get "/results/mediums/:id", to: "mediums#filter", as: "medium"
  get "/results/artists", to: "artists#index", as: "artists"
  get "/contents", to: "contents#index", as: "contents"

  # ARTWORK CRUD

  get "/results/artwork/:id", to: "contents#show", as: "content"
  get "/sell", to: "contents#new", as: "new_content"
  post "/contents", to: "contents#create"
  get "/results/artwork/:id/edit", to: "contents#edit", as: "edit_content"
  patch "/results/artwork/:id", to: "contents#update"
  delete "/results/artwork/:id", to: "contents#destroy", as: "delete_content"

  #PAYMENT

  get "/orders/success", to: "orders#success", as: "payment_success"
  post "/webhook", to: "orders#webhook", as: "order"

 #PROFILE CRUD
  get "/profile", to: "profiles#index", as: "profile"
  get "/profile/edit", to: "profiles#edit", as: "edit_profile"
  get "/profile/:id", to: "artists#show", as: "profile_id"
  patch "/profile", to: "profiles#update"
  delete "/profile", to: "profiles#destroy", as: "delete_profile"

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    def index
        @artworks_all = Content.all #collects all artwork data and stores in instand variable @artworks_all
        @artists_all = User.all #collects all artist data and stores in instance variable @artist_all
        @artist = User.find_by_id(params[:id])
    end

    def show
        @artist = User.find_by_id(params[:id])
        @content = Content.find_by_id(params[:id])
        @artist_content = @artist.contents
    end

end

app/views/artists/index.html.erb
<main id="artist-index">

    <%= render "/nav_bar" %>

    <div class="heading">
        <h1>Artists</h1>
    </div>

    <%= render "/back_button" %>
    
    <nav class="category-search">
        <div class="nav-element">
            <p><%= link_to "genre", genres_path,  :class => "link-to" %></p>
            <p><%= link_to "artist", artists_path, :class => "link-to"%></p>
            <p><%= link_to "medium", mediums_path, :class => "link-to"%></p>
            <p><%= link_to "all", results_all_path, :class => "link-to"%></p>

        </div>
    </nav>    

    <div class="flexbox">
        <% @artists_all.each do |artist| %>
            <div class="listings">
                <%=link_to profile_id_path(artist), class: "link-to" do %>
                <%= image_tag artist.pic if artist.pic.attached? %>
                <h2><%= artist.username %></h2>
                <p><%= artist.bio %></p>
                <%end%>
            </div>
        <% end %>
    </div>
</main>        

app/views/artists/show.html.erb
<main id="profile-show">

    <%= render "/nav_bar" %>

    <div class="profile-picture">
        <div class="pic-div"><%= image_tag @artist.pic, class: "user-pic" %></div>
    </div>

    <h1>
        <%= @artist.name %>
    </h1>

    <p> 
        <%=@artist.bio%>
    </p>        

    <div class="line"></div>

    <div class="user-art">

        <h2><%=@artist.name%>'s work</h2>

            <div class="flexbox">
                <% @artist_content.each do |artwork| %>
                    <div class="listings">
                        <%=link_to content_path(artwork), class: "link-to" do %>
                            <%= image_tag artwork.pic if artwork.pic.attached? %>
                            <h2>
                            <%= artwork.title %>
                            </h2>
                            <p><%= number_to_currency(artwork.price / 100.0) %></p>
                        <%end%>
                    </div> 
                <% end %>
            </div>
    </div>


</main>