config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #STATIC pages
  
  get "/", to: "pages#welcome", as: "root"
  get "/home", to: "pages#home", as: "home"
  get "/explore", to: "pages#explore", as: "explore"
  # get "/learn", to: "pages#learn", as: "learn" #this was a sprinkle
  get "/contact", to: "pages#contact", as: "contact"

  # FILTER RESULTS

  get "/results/all", to: "contents#index", as: "results_all"
  get "/results/genres", to: "genres#index", as: "genres"
  get "/results/genres/:id", to: "genres#filter", as: "genre"
  get "/results/mediums", to: "mediums#index", as: "mediums"
  get "/results/mediums/:id", to: "mediums#filter", as: "medium"
  get "/results/artists", to: "artists#index", as: "artists"
  get "/contents", to: "contents#index", as: "contents"

  # ARTWORK CRUD

  get "/results/artwork/:id", to: "contents#show", as: "content"
  get "/sell", to: "contents#new", as: "new_content"
  post "/contents", to: "contents#create"
  get "/results/artwork/:id/edit", to: "contents#edit", as: "edit_content"
  patch "/results/artwork/:id", to: "contents#update"
  delete "/results/artwork/:id", to: "contents#destroy", as: "delete_content"

  #PAYMENT

  get "/orders/success", to: "orders#success", as: "payment_success"
  post "/webhook", to: "orders#webhook", as: "order"

 #PROFILE CRUD
  get "/profile", to: "profiles#index", as: "profile"
  get "/profile/edit", to: "profiles#edit", as: "edit_profile"
  get "/profile/:id", to: "artists#show", as: "profile_id"
  patch "/profile", to: "profiles#update"
  delete "/profile", to: "profiles#destroy", as: "delete_profile"

end

app/views/pages/_nav_bar.html.erb
    <div class="nav_bar">
        <div class="search">
            <input type="text" placeholder="Search"/>
        </div>
        <!--buttons for desktop (display off for phone) -->

        <form action="/INSERTROUTE" class="desktop_nav">
            <button>test</button>
        </form>

        <!--dropdown menu -->

        <div class="dropdown">
            <button class="dropbtn">Menu</button>
                <div class="dropdown-content">
                    <a href="aboutme.html">Explore</a>
                    <a href="contact.html">Sell</a>
                    <a href="content.html">Learn</a>
                    <a href="blog.html">Profile</a>
                    <a href="index.html">Contact</a>
                </div>
        </div>
    </div>

app/views/pages/contact.html.erb
<main id="contact">
    <%= render "/nav_bar" %>
    <!-- insert nav bar here -->

    <h1> Need to contact us?</h1>
    <p> 
        Sweet roll dessert liquorice. Caramels macaroon chupa chups marzipan powder cheesecake sugar plum. Pudding bear claw jelly beans muffin caramels danish. Cheesecake cake cake liquorice pudding tart gingerbread jelly topping. Lemon drops danish cheesecake chupa chups caramels cookie tootsie roll.
    </p>

</main>

app/views/pages/explore.html.erb
<div id="explore_page">
    <%= render "/nav_bar" %>

    <h1>Explore</h1>

    <div class="flexbox">

        <div class="medium-image">
            <%= link_to mediums_path, :class => "link-to" do %>
                <div>
                    <p>Medium</p>
                </div>
            <%end%>
        </div>

        <div class="genre-image">
            <%= link_to genres_path, :class => "link-to" do %>
                <div>
                    <p>Genre</p>
                </div>
            <%end%>
        </div>

        <div class="artist-image">
            <%= link_to artists_path, :class => "link-to" do %>
                <div>
                    <p>Artist</p>
                </div>
            <%end%>
        </div>

        <div class="all-image">
            <%= link_to results_all_path, :class => "link-to" do %>
                <div>
                    <p>All</p>
                </div>
            <%end%>
        </div>

    </div>

    <footer>
    </footer>
</div>

app/views/pages/home.html.erb
<main id="home_page">

    <%= render "/nav_bar" %>

    <!--pictures and paras -->

        <h1>BUY!<h1>

        <div class="buy-image"></div>

        <h6>
            Topping gummies marzipan powder chocolate gummies ice cream. Lollipop macaroon sesame snaps chocolate cake chupa chups cookie. Fruitcake cheesecake liquorice. Sweet powder chupa chups. Cheesecake topping liquorice chocolate macaroon jelly-o. Fruitcake biscuit macaroon toffee gummies marzipan pie. Bonbon sesame snaps cheesecake lemon drops marshmallow.
        </h6>

        <div class="p">
            <p><%= link_to "explore", explore_path, :class => "link-to"%></p>
        </div>
        <h6>____________________________________________________________________</h6>


        <h1>SELL!<h1>

        <div class="sell-image"></div>

        <h6>
            Topping gummies marzipan powder chocolate gummies ice cream. Lollipop macaroon sesame snaps chocolate cake chupa chups cookie. Fruitcake cheesecake liquorice. Sweet powder chupa chups. Cheesecake topping liquorice chocolate macaroon jelly-o. Fruitcake biscuit macaroon toffee gummies marzipan pie. Bonbon sesame snaps cheesecake lemon drops marshmallow.
        </h6>

        <div class="p">
            <p><%= link_to "sell", new_content_path, :class => "link-to"%></p>
        </div>

        <h6>____________________________________________________________________</h6>


        <h1>LEARN!<h1>

        <div class="learn-image"></div>

        <h6>
            Topping gummies marzipan powder chocolate gummies ice cream. Lollipop macaroon sesame snaps chocolate cake chupa chups cookie. Fruitcake cheesecake liquorice. Sweet powder chupa chups. Cheesecake topping liquorice chocolate macaroon jelly-o. Fruitcake biscuit macaroon toffee gummies marzipan pie. Bonbon sesame snaps cheesecake lemon drops marshmallow.
        </h6>

        <div class="p">
            <p><%= link_to "learn", home_path, :class => "link-to"%></p>
        </div>

</main>

app/views/pages/payment_success.erb
<h1> this is the payment success page yay!</h1>

app/views/pages/results.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <!-- insert nav bar here -->
    <!-- search by catagory at top -->
    <nav>
        <%= Genre.title.list_all %>

    </nav>
</body>
</html>

app/views/pages/welcome.html.erb
<div id="welcome_page">

  <div class="background-image">

    <h1>Welcome to The Art Club</h1>

    <div class="flexbox">
      <!-- continue as guest button -->
      <div class="guest">
        <%= link_to "Continue as guest", home_path, :class => "link-to"%>
      </div>
        
      <h3>OR</h3>

        <!--sign up form -->
      <section class="signup">
          <h4>Join The Art Club!</h4>

          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= render "devise/shared/error_messages", resource: resource %>

              <div class="field">
                  <%= f.label :name %><br />
                  <%= f.text_field :name, autofocus: true, autocomplete: "name" %>
              </div>

                  <div class="field">
                  <%= f.label :username %><br />
                  <%= f.text_field :username, autofocus: true, autocomplete: "username" %>
              </div>

              <div class="field">
                  <%= f.label :email %><br />
                  <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
              </div>

              <div class="field">
                  <%= f.label :password %>
                  <% if @minimum_password_length %>
                  <em>(<%= @minimum_password_length %> characters minimum)</em>
                  <% end %><br />
                  <%= f.password_field :password, autocomplete: "new-password" %>
              </div>

              <div class="field">
                  <%= f.label :password_confirmation %><br />
                  <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
              </div>

              <div class="actions">
                  <p><%= f.submit "Sign up", class: "button" %></p>
              </div>
          <% end %>

          <%- if controller_name != 'sessions' %>
          <p><%= link_to "Log in", new_session_path(resource_name), class: "button"  %><br /></p>
          <p><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "button" %></p>
          <% end %>
      </section>

      <section class="login">

      </section>
    </div>
  </div>

</div>